#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BREW_DIR="dotbot-brew"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule sync --quiet --recursive

SUBMODULES=("${DOTBOT_DIR}")
if git ls-files --stage -- "${DOTBOT_BREW_DIR}" | grep -q '^160000 '; then
  SUBMODULES+=("${DOTBOT_BREW_DIR}")
fi

git submodule update --init --recursive "${SUBMODULES[@]}"

DOTBOT_ARGS=(
  -d "${BASEDIR}"
  -c "${CONFIG}"
  "${@}"
)

if [[ -d "${BASEDIR}/${DOTBOT_BREW_DIR}" ]]; then
  DOTBOT_ARGS=(--plugin-dir "${DOTBOT_BREW_DIR}" "${DOTBOT_ARGS[@]}")
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" "${DOTBOT_ARGS[@]}"
