[Addon]
Name=Rime Chinese Mode Reset
Name[zh_CN]=Rime 中文模式重置
Comment=Keep Rime in Chinese mode when switching input methods
Comment[zh_CN]=切换输入法时保持 Rime 为中文输入模式
Category=Module
Type=Lua
OnDemand=False
Configurable=False
Library=main.lua

[Addon/Dependencies]
0=luaaddonloader
